# Generated by Django 4.2.16 on 2024-11-15 10:10

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("h1", 0),
                    ("h2", 0),
                    ("paragraph", 1),
                    ("image_text", 4),
                    ("image_carousel", 5),
                    ("thumbnail_gallery", 5),
                ],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {}),
                    1: ("wagtail.blocks.RichTextBlock", (), {}),
                    2: ("wagtail.blocks.BooleanBlock", (), {"required": False}),
                    3: ("blog.blocks.CustomImageChooserBlock", (), {}),
                    4: (
                        "wagtail.blocks.StructBlock",
                        [[("reverse", 2), ("text", 1), ("image", 3)]],
                        {},
                    ),
                    5: ("wagtail.blocks.ListBlock", (3,), {}),
                },
            ),
        ),
    ]
